# Generated by Django 5.2.15 on 2026-07-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_password_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(max_length=100)),
                ('pay', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
